--
-- PostgreSQL database dump
--

\restrict AfScHuPNM7cmZNmtkYRCL1H2oSOIJ3e4KmkkNKohw6HHAGFFxHrzGU7mLUcthkO

-- Dumped from database version 14.20 (Homebrew)
-- Dumped by pg_dump version 17.7 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: yes
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO yes;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: 거래; Type: TABLE; Schema: public; Owner: bankuser
--

CREATE TABLE public."거래" (
    "거래_id" bigint NOT NULL,
    "금액" bigint NOT NULL,
    "생성일시" timestamp(6) without time zone,
    "출금_계좌_id" bigint NOT NULL,
    "거래상태" character varying(255) NOT NULL,
    "입금_계좌_id" bigint NOT NULL,
    "거래_추적_id" character varying(255) NOT NULL,
    "거래유형" character varying(255) NOT NULL
);


ALTER TABLE public."거래" OWNER TO bankuser;

--
-- Name: 거래_거래_id_seq; Type: SEQUENCE; Schema: public; Owner: bankuser
--

ALTER TABLE public."거래" ALTER COLUMN "거래_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."거래_거래_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: 계좌; Type: TABLE; Schema: public; Owner: bankuser
--

CREATE TABLE public."계좌" (
    id bigint NOT NULL,
    "계좌번호" character varying(255) NOT NULL,
    "잔액" bigint NOT NULL,
    "사용자_id" character varying(255) NOT NULL,
    "상품" character varying(255) DEFAULT '입출금계좌'::character varying NOT NULL,
    "상태" character varying(255) DEFAULT 'NORMAL'::character varying NOT NULL,
    "버전" integer DEFAULT 0 NOT NULL,
    "생성일시" timestamp without time zone DEFAULT now(),
    "해지일시" timestamp without time zone
);


ALTER TABLE public."계좌" OWNER TO bankuser;

--
-- Name: 계좌_id_seq; Type: SEQUENCE; Schema: public; Owner: bankuser
--

ALTER TABLE public."계좌" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."계좌_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: 계좌_변경_이력; Type: TABLE; Schema: public; Owner: bankuser
--

CREATE TABLE public."계좌_변경_이력" (
    "이력_id" bigint NOT NULL,
    "계좌_id" bigint NOT NULL,
    "이후_잔액" bigint,
    "생성일시" timestamp(6) without time zone,
    "이전_잔액" bigint,
    "변경_사유" character varying(255),
    "거래_id" bigint NOT NULL
);


ALTER TABLE public."계좌_변경_이력" OWNER TO bankuser;

--
-- Name: 계좌_변경_이력_이력_id_seq; Type: SEQUENCE; Schema: public; Owner: bankuser
--

ALTER TABLE public."계좌_변경_이력" ALTER COLUMN "이력_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."계좌_변경_이력_이력_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: 계좌_인증; Type: TABLE; Schema: public; Owner: bankuser
--

CREATE TABLE public."계좌_인증" (
    "계좌_id" bigint NOT NULL,
    "생성일시" timestamp(6) without time zone,
    "실패_횟수" integer NOT NULL,
    "마지막_실패_일시" timestamp(6) without time zone,
    pin_hash character varying(255) NOT NULL,
    pin_salt character varying(255) NOT NULL,
    "인증_상태" character varying(255) NOT NULL,
    "수정일시" timestamp(6) without time zone
);


ALTER TABLE public."계좌_인증" OWNER TO bankuser;

--
-- Name: 리프레시_토큰; Type: TABLE; Schema: public; Owner: bankuser
--

CREATE TABLE public."리프레시_토큰" (
    "토큰_id" bigint NOT NULL,
    "만료일시" timestamp(6) without time zone,
    "토큰" character varying(255) NOT NULL,
    "사용자_id" character varying(20)
);


ALTER TABLE public."리프레시_토큰" OWNER TO bankuser;

--
-- Name: 리프레시_토큰_토큰_id_seq; Type: SEQUENCE; Schema: public; Owner: bankuser
--

ALTER TABLE public."리프레시_토큰" ALTER COLUMN "토큰_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."리프레시_토큰_토큰_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: 사용자; Type: TABLE; Schema: public; Owner: bankuser
--

CREATE TABLE public."사용자" (
    "사용자_id" character varying(20) NOT NULL,
    "생성일시" timestamp(6) without time zone NOT NULL,
    "이메일" character varying(255) NOT NULL,
    "사용자_pw" character varying(255) NOT NULL,
    "역할" character varying(255) NOT NULL,
    "상태" character varying(255) NOT NULL
);


ALTER TABLE public."사용자" OWNER TO bankuser;

--
-- Name: 사용자_프로필; Type: TABLE; Schema: public; Owner: bankuser
--

CREATE TABLE public."사용자_프로필" (
    "사용자_id" character varying(20) NOT NULL,
    "생성일시" timestamp(6) without time zone,
    "이름" character varying(255) NOT NULL,
    "핸드폰번호" character varying(255),
    "주민번호_암호화" character varying(255) NOT NULL,
    "수정일시" timestamp(6) without time zone,
    "주소" character varying(255)
);


ALTER TABLE public."사용자_프로필" OWNER TO bankuser;

--
-- Name: 사용자 uk2h8xpwfdg83r6ndi8vgn0wu8; Type: CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public."사용자"
    ADD CONSTRAINT uk2h8xpwfdg83r6ndi8vgn0wu8 UNIQUE ("이메일");


--
-- Name: 리프레시_토큰 uk5vmlih8ut28elexl7wrs1n902; Type: CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public."리프레시_토큰"
    ADD CONSTRAINT uk5vmlih8ut28elexl7wrs1n902 UNIQUE ("사용자_id");


--
-- Name: 거래 ukpotqc2mo8mmm2e2g09jgfqr4w; Type: CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public."거래"
    ADD CONSTRAINT ukpotqc2mo8mmm2e2g09jgfqr4w UNIQUE ("거래_추적_id");


--
-- Name: 거래 거래_pkey; Type: CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public."거래"
    ADD CONSTRAINT "거래_pkey" PRIMARY KEY ("거래_id");


--
-- Name: 계좌 계좌_pkey; Type: CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public."계좌"
    ADD CONSTRAINT "계좌_pkey" PRIMARY KEY (id);


--
-- Name: 계좌_변경_이력 계좌_변경_이력_pkey; Type: CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public."계좌_변경_이력"
    ADD CONSTRAINT "계좌_변경_이력_pkey" PRIMARY KEY ("이력_id");


--
-- Name: 계좌_인증 계좌_인증_pkey; Type: CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public."계좌_인증"
    ADD CONSTRAINT "계좌_인증_pkey" PRIMARY KEY ("계좌_id");


--
-- Name: 계좌 계좌번호_unique; Type: CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public."계좌"
    ADD CONSTRAINT "계좌번호_unique" UNIQUE ("계좌번호");


--
-- Name: 리프레시_토큰 리프레시_토큰_pkey; Type: CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public."리프레시_토큰"
    ADD CONSTRAINT "리프레시_토큰_pkey" PRIMARY KEY ("토큰_id");


--
-- Name: 사용자 사용자_pkey; Type: CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public."사용자"
    ADD CONSTRAINT "사용자_pkey" PRIMARY KEY ("사용자_id");


--
-- Name: 사용자_프로필 사용자_프로필_pkey; Type: CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public."사용자_프로필"
    ADD CONSTRAINT "사용자_프로필_pkey" PRIMARY KEY ("사용자_id");


--
-- Name: 리프레시_토큰 fk_리프레시_토큰_사용자; Type: FK CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public."리프레시_토큰"
    ADD CONSTRAINT "fk_리프레시_토큰_사용자" FOREIGN KEY ("사용자_id") REFERENCES public."사용자"("사용자_id");


--
-- Name: 사용자_프로필 fkcd9ivot3ps9a5ekivsxj8t0xm; Type: FK CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public."사용자_프로필"
    ADD CONSTRAINT fkcd9ivot3ps9a5ekivsxj8t0xm FOREIGN KEY ("사용자_id") REFERENCES public."사용자"("사용자_id");


--
-- Name: 계좌 fkm9ixltjm6owobtik1415ckndv; Type: FK CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public."계좌"
    ADD CONSTRAINT fkm9ixltjm6owobtik1415ckndv FOREIGN KEY ("사용자_id") REFERENCES public."사용자"("사용자_id");


--
-- Name: 계좌_인증 fkrb20rdc34lvri8p36kuwosvmb; Type: FK CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public."계좌_인증"
    ADD CONSTRAINT fkrb20rdc34lvri8p36kuwosvmb FOREIGN KEY ("계좌_id") REFERENCES public."계좌"(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: yes
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict AfScHuPNM7cmZNmtkYRCL1H2oSOIJ3e4KmkkNKohw6HHAGFFxHrzGU7mLUcthkO

